export const jsonMock = {
  input_data: {
    dur: 1.1e-05,
    proto: "udp",
    service: "-",
    state: "INT",
    spkts: 2,
    dpkts: 0,
    sbytes: 104,
    dbytes: 0,
    rate: 90909.0902,
    sttl: 254,
    dttl: 0,
    sload: 37818180.0,
    dload: 0.0,
    sloss: 0,
    dloss: 0,
    sinpkt: 1.1e-05,
    dinpkt: 0.0,
    sjit: 0.0,
    djit: 0.0,
    swin: 0,
    stcpb: 0,
    dtcpb: 0,
    dwin: 0,
    tcprtt: 0.0,
    synack: 0.0,
    ackdat: 0.0,
    smean: 52,
    dmean: 0,
    trans_depth: 0,
    response_body_len: 0,
    ct_srv_src: 2,
    ct_state_ttl: 2,
    ct_dst_ltm: 1,
    ct_src_dport_ltm: 1,
    ct_dst_sport_ltm: 1,
    ct_dst_src_ltm: 1,
    is_ftp_login: 0,
    ct_ftp_cmd: 0,
    ct_flw_http_mthd: 0,
    ct_src_ltm: 1,
    ct_srv_dst: 2,
    is_sm_ips_ports: 0
  },
  result: {
    prediction: "Normal",
    is_anomaly: false,
    confidence: 0.975,
    probabilities: {
      Backdoor: 0.0,
      Normal: 0.975,
      Worms: 0.025
    }
  }
}